### ISSUE TITLE
The PSP rando is broken

### ISSUE THREAD

**Issue by SenseiLeRoof** [MottZilla/SOTN_AR#2]
It quits immediately with a dialog "Error opening ISO or invalid file". The randomizer window says it couldn't allocate memory to load BIN. I've made sure my ISO matches the Redump entry.

**Comment by MottZilla** [comment]
What are your system details? Operating system, amount of RAM, using SDD or Hard Disk, etc. That Error message indicates it could not allocate enough memory to load the ISO into RAM. Failing at this point means it didn't even get to the point where it tries to verify the file is the PSP version.

**Comment by SenseiLeRoof** [comment]
Win10 (22H2), 16GB RAM. All relevant files are on the same external HD. The ISO itself is only 1.1 GB or so and SotN is about half of that, so it should easily be more than enough.

**Comment by MottZilla** [comment]
The error is happening because malloc() isn't returning a pointer to memory to load the ISO into. But as you said I don't see the reason why this would be. You have plenty of memory. You could try setting the Input and Output files to the same file (so it will patch in place) to see if that works. I am curious if that will work.

I could try changing the way it allocates memory for when it needs to copy from input to output so that it uses multiple smaller chunks. But first let me know if using the same file as input and output works.

**Comment by SenseiLeRoof** [comment]
Using the same file results in a successful rando.

(I also forgot to note previously that checking Create PPF still resulted in the error.)

**Comment by MottZilla** [comment]
The Create PPF button is not functional in the current public build. The next build will have it operational. It's still very strange that it does not like allocating the large amount of memory even though it isn't that much more than for PS1 and Saturn. 

I can try adding some handling to attempt to split it into smaller chunks if it can't allocate enough memory. But I can't reproduce the error on my system.

Edit: Allocating a much smaller chunk and copying the file from Input to Output before patching seems much faster and perhaps won't cause the error on your system. The next build should have that.

**Comment by MottZilla** [comment]
Please tell me if the new version release 12-31-2023 fixes your issue using separate Input and Output files.

**Comment by SenseiLeRoof** [comment]
Success!
